package com.example.kotlin.model.errors

class AuthException: Throwable()